import { PropsWithChildren } from "react";
import { QueryProvider } from "@/providers/query-provider";
import { SheetsProvider } from "@/providers/sheets-provider";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";
import "@/app/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: Readonly<PropsWithChildren>) => (
  <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <SheetsProvider />
          <Toaster />
          {children}
        </QueryProvider>
      </body>
    </html>
  </ClerkProvider>
);

export default RootLayout;
